services:
  # Unified Web Service (One Link)
  - type: web
    name: automation-tool-all-in-one
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
